/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rossrkk' at '02/01/17 00:32' with Gradle 3.0
 *
 * @author rossrkk, @date 02/01/17 00:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
